# Generated by Django 3.0.4 on 2020-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='table',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
